[package]
name = "raytrace"
version = "0.1.0"
authors = ["Dominique Poudevigne <dompdv@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timeit = "0.1.2"
minifb = "0.16"
rand = "0.7.3"
